In [1]:
import numpy as np

In [2]:
weights = np.array([1,2,3])

In [3]:
weights

array([1, 2, 3])

In [4]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
np.ones([2,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.random.rand(5)

array([0.47465672, 0.21551513, 0.64782273, 0.21452841, 0.385297  ])

In [8]:
np.random.randn(2,3)

array([[-0.66735161,  1.39719556, -0.95388925],
       [-1.4471835 , -0.06574722,  0.40263806]])

In [9]:
np.full([2,3],42)

array([[42, 42, 42],
       [42, 42, 42]])

In [10]:
np.arange(10,90,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [11]:
np.arange(10,90,3).shape

(27,)

In [12]:
np.arange(10,90,3).reshape(3,3,3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [13]:
np.arange(10,90,3).reshape(3,9)

array([[10, 13, 16, 19, 22, 25, 28, 31, 34],
       [37, 40, 43, 46, 49, 52, 55, 58, 61],
       [64, 67, 70, 73, 76, 79, 82, 85, 88]])

In [14]:
np.arange(10,90,3).reshape(3,3,-1)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [15]:
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [16]:
np.linspace(3,27,18)

array([ 3.        ,  4.41176471,  5.82352941,  7.23529412,  8.64705882,
       10.05882353, 11.47058824, 12.88235294, 14.29411765, 15.70588235,
       17.11764706, 18.52941176, 19.94117647, 21.35294118, 22.76470588,
       24.17647059, 25.58823529, 27.        ])